spring:
  datasource:
    url: jdbc:sqlite::memory:
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

jwt:
  secret: test-secret-key
  expiration: 86400000

file:
  upload:
    dir: test-uploads

logging:
  level:
    com.couplewebsite: DEBUG
    org.springframework.security: WARN
    org.hibernate: WARN
