[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
VITE_API_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}"
NODE_ENV = "production"

[environments.production.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300