[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
SPRING_PROFILES_ACTIVE = "production"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
JWT_SECRET = "${{JWT_SECRET}}"
CORS_ORIGINS = "https://${{RAILWAY_PUBLIC_DOMAIN}}"

[environments.production.deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300