[build]
# Railway will auto-detect Spring Boot application
builder = "nixpacks"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/*.jar"
rootDirectory = "spring-backend"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# GitHub Integration
[environments.production]
# Railway will automatically deploy when you push to GitHub
# Environment variables are loaded from .env.production and can be overridden in Railway dashboard

[environments.production.variables]
# Core Application Settings
SPRING_PROFILES_ACTIVE = "production"
PORT = "8080"
UPLOAD_DIR = "/app/uploads"

# Database Configuration - Railway will inject DATABASE_URL automatically
# These will be overridden by Railway's PostgreSQL service
DATABASE_DRIVER = "org.postgresql.Driver"
DATABASE_PLATFORM = "org.hibernate.dialect.PostgreSQLDialect"

# Security Configuration (using default value from .env.production)
JWT_SECRET = "couple-website-super-secret-jwt-key-for-production-2024-railway"

# CORS Configuration - allow Railway domain and common development origins
CORS_ORIGINS = "https://${{RAILWAY_PUBLIC_DOMAIN}},http://localhost:5173,http://localhost:3000"

[environments.production.deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300