[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# GitHub Integration
[environments.production]
# Railway will automatically deploy when you push to GitHub
# Environment variables are loaded from .env.production and can be overridden in Railway dashboard

[environments.production.variables]
# Core Application Settings
SPRING_PROFILES_ACTIVE = "production"
PORT = "8080"
UPLOAD_DIR = "/app/uploads"

# Database Configuration (using default values from .env.production)
POSTGRES_DB = "couple_website"
POSTGRES_USER = "couple_user"
POSTGRES_PASSWORD = "couple_secure_password_2024"
DATABASE_URL = "jdbc:postgresql://db:5432/couple_website?user=couple_user&password=couple_secure_password_2024"
DATABASE_DRIVER = "org.postgresql.Driver"
DATABASE_PLATFORM = "org.hibernate.dialect.PostgreSQLDialect"
SPRING_DATASOURCE_URL = "jdbc:postgresql://db:5432/couple_website"
SPRING_DATASOURCE_USERNAME = "couple_user"
SPRING_DATASOURCE_PASSWORD = "couple_secure_password_2024"
SPRING_DATASOURCE_DRIVER_CLASS_NAME = "org.postgresql.Driver"

# Security Configuration (using default value from .env.production)
JWT_SECRET = "couple-website-super-secret-jwt-key-for-production-2024-railway"

# CORS Configuration (will be set to your Railway domain)
CORS_ORIGINS = "https://${{RAILWAY_PUBLIC_DOMAIN}}"

[environments.production.deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300