[build]
builder = "nixpacks"
buildCommand = "cd client && npm ci && npm run build && cd ../spring-backend && mvnw.cmd clean package -DskipTests"

[deploy]
startCommand = "cd spring-backend && java -jar target/*.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
SPRING_PROFILES_ACTIVE = "production"
SERVER_PORT = "$PORT"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
JWT_SECRET = "${{JWT_SECRET}}"
NODE_ENV = "production"

[environments.production.deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300