[build]
# Use Dockerfile for multi-stage build (React + Spring Boot)
builder = "dockerfile"

# Build-time environment variables for Vite
[build.env]
VITE_API_URL = "https://www.qimiao.life"
RAILWAY_PUBLIC_DOMAIN = "${{RAILWAY_PUBLIC_DOMAIN}}"

# Runtime configuration
[deploy]
# Let Dockerfile CMD handle the startup command
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# GitHub Integration
[environments.production]
# Railway will automatically deploy when you push to GitHub
# Environment variables are loaded from .env.production and can be overridden in Railway dashboard

[environments.production.variables]
# Core Application Settings
SPRING_PROFILES_ACTIVE = "production"
PORT = "8080"
UPLOAD_DIR = "/app/uploads"

# Database Configuration - Using PostgreSQL for persistent data storage
# Railway will automatically provide PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD
# when you add a PostgreSQL database service to your project

# Security Configuration - IMPORTANT: Change this to a secure random string
JWT_SECRET = "couple-website-super-secret-jwt-key-for-production-2024-railway"

# CORS Configuration - allow Railway domain, custom domain, and common development origins
CORS_ORIGINS = "https://${{RAILWAY_PUBLIC_DOMAIN}},https://www.qimiao.life,http://localhost:5173,http://localhost:3000"

[environments.production.deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300