# This is a monorepo root - not meant to be deployed as a service
# Railway should automatically detect and deploy:
# - client/ directory as a React/Vite service
# - spring-backend/ directory as a Java/Maven service
#
# Each subdirectory has its own railway.toml configuration

[build]
builder = "nixpacks"

[deploy]
# This configuration should not be used for deployment
# Individual services in subdirectories will handle their own deployment
startCommand = "echo 'This is a monorepo root. Deploy individual services instead.' && exit 1"
